# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_wrapper_poismf <- function(A, B, dimA, dimB, k, Xr, Xr_ind_int, Xr_indptr_int, Xc, Xc_ind_int, Xc_indptr_int, nnz, l1_reg, l2_reg, niter, npass, step_size, use_cg, nthreads) {
    invisible(.Call(`_poismf_r_wrapper_poismf`, A, B, dimA, dimB, k, Xr, Xr_ind_int, Xr_indptr_int, Xc, Xc_ind_int, Xc_indptr_int, nnz, l1_reg, l2_reg, niter, npass, step_size, use_cg, nthreads))
}

predict_multiple <- function(A, B, k, npred, ia, ib, out, nthreads) {
    invisible(.Call(`_poismf_predict_multiple`, A, B, k, npred, ia, ib, out, nthreads))
}

factorize_single <- function(a_vector, x, ix, nnz, B, Bsum, k, l2_reg) {
    invisible(.Call(`_poismf_factorize_single`, a_vector, x, ix, nnz, B, Bsum, k, l2_reg))
}

